baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MathExLab'
theme = 'ananke'

[markup.goldmark.renderer]
unsafe = true

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "/no_fill.011_side.png"
description = "Mathematical and Computational Lab for Complex Systems"
custom_css = ["css/custom.css"]
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
mainSections = ["positions", "research-highlights", "seminars"]

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/mathexlab"
